name: simlk_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  app_settings: ^4.1.6
  badges: ^2.0.3
  cached_network_image: ^3.1.0
  carousel_slider: ^4.1.1
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dotted_border: ^2.0.0+3
  dotted_line: ^3.1.0
  expandable_text: ^2.3.0
  file_picker: ^4.6.1
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4
  firebase_analytics: ^9.3.8
  flutter:
    sdk: flutter
  flutter_downloader: ^1.9.0
  flutter_local_notifications: ^12.0.1+1
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.0.3
  freezed: ^0.14.2
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: 2.2.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.2
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pull_to_refresh_flutter3: ^2.0.1
  retrofit: ^3.0.1+1
  retrofit_generator: any
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.1
  permission_handler: ^10.2.0
  remixicon: ^1.0.0
  sizer: ^2.0.15
  shimmer: ^2.0.0
  table_calendar: ^3.0.7
  timelines: ^0.1.0

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner:

flutter_gen:
  output: lib/src/res/gen/
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/src/res/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
